# Helper function
nonempty <- function(x) !is.null(x) && length(x) == 1L && !is.na(x) && nchar(x) > 0

#' @keywords internal
generate_r_file <- function(parsed, namespace, seen_global = NULL) {
  # R wrappers use their own local dedup — they do NOT write to seen_global.
  # seen_global is only consulted to skip R wrappers for C functions that
  # were already emitted in a previous namespace's C file.
  local_seen <- character()
  unique_fns <- Filter(function(f) {
    sym <- f$c_symbol
    if (sym %in% local_seen) return(FALSE)
    if (!is.null(seen_global) && sym %in% seen_global$symbols) return(FALSE)
    local_seen <<- c(local_seen, sym)
    TRUE
  }, parsed$functions)
  # Do NOT update seen_global here — only generate_c_file owns that.
  r_fns <- sapply(unique_fns, function(fn) generate_r_function(fn, namespace))
  r_fns <- r_fns[nchar(r_fns) > 0]

  enums <- sapply(parsed$enums, function(e) {
    vals <- paste0(toupper(names(e$values)), " <- ", e$values)
    sprintf("\n# %s\n%s", e$name, paste(vals, collapse="\n"))
  })
  paste(c("# Autogenerated R wrappers", r_fns, "\n# Enumerations", enums),
        collapse="\n")
}

r_name_from_c <- function(c_symbol, namespace) {
  # Keep full name to avoid collisions (e.g. g_application_new vs gtk_application_new)
  # Just convert snake_case to camelCase
  pts <- strsplit(c_symbol, "_")[[1]]
  if (length(pts) <= 1) return(c_symbol)

  # camelCase: first word lower, rest capitalised
  tail <- paste0(
    toupper(substring(pts[-1], 1, 1)),
    substring(pts[-1], 2),
    collapse = ""
  )
  paste0(pts[1], tail)
}

generate_r_function <- function(fn, namespace) {
  if (!nonempty(fn$c_symbol)) return("")
  if (any(sapply(fn$params, function(p)
    identical(p$name,"...") || identical(p$type$gi,"GLib.VarArgs")))) return("")
  if (grepl("^g_atomic_|^g_once_init_|^g_pointer_bit_", fn$c_symbol)) return("")
  if (grepl("^g_io_module_", fn$c_symbol)) return("")

  # Skip platform-specific functions
  platform_function_patterns <- c(
    "^gtk_page_setup_unix_dialog_",
    "^gtk_print_unix_dialog_",
    "^gtk_print_job_",
    "^gtk_printer_",
    "^g_osx_app_info_",
    "^g_file_descriptor_based_",
    "^g_unix_connection_",
    "^g_unix_credentials_",
    "^g_unix_fd_",
    "^g_unix_input_",
    "^g_unix_mount_",
    "^g_unix_output_",
    "^g_unix_socket_"
  )

  if (any(sapply(platform_function_patterns, function(pattern) {
    grepl(pattern, fn$c_symbol)
  }))) return("")

  if (any(sapply(fn$params, function(p) {
    if (!identical(p$direction,"in")) return(FALSE)
    gi <- p$type$gi; nonempty(gi) && grepl("Func$|Notify$|Callback$|^GLib\\.VarArgs", gi)
  }))) return("")

  r_name    <- r_name_from_c(fn$c_symbol, namespace)
  in_params <- Filter(function(p) identical(p$direction,"in"), fn$params)

  # Use actual parameter names from GIR, sanitized for R
  args <- if (length(in_params) > 0) {
    sapply(in_params, function(p) {
      name <- p$name
      # Sanitize: replace invalid R identifier characters
      name <- gsub("[^a-zA-Z0-9_]", "_", name)
      # Avoid R keywords
      if (name %in% c("if", "else", "for", "while", "function", "return", "break", "next", "repeat", "in", "NULL", "TRUE", "FALSE", "NA", "NaN", "Inf")) {
        name <- paste0(name, "_")
      }
      # Ensure doesn't start with a number
      if (grepl("^[0-9]", name)) {
        name <- paste0("x", name)
      }
      name
    })
  } else {
    character(0)
  }

  args_csv  <- paste(args, collapse=", ")
  call_args <- if (length(args)>0) paste0(", ", args_csv) else ""

  # Generate roxygen2 documentation
  # Create @param entries for each parameter
  param_docs <- if (length(in_params) > 0) {
    sapply(seq_along(in_params), function(i) {
      p <- in_params[[i]]
      param_name <- args[i]
      # Basic type description from GI type
      type_desc <- if (!is.null(p$type$gi) && !is.na(p$type$gi)) {
        p$type$gi
      } else if (!is.null(p$type$c) && !is.na(p$type$c)) {
        p$type$c
      } else {
        "parameter"
      }
      sprintf("#' @param %s %s", param_name, type_desc)
    })
  } else {
    character(0)
  }

  # Return type description
  ret_desc <- if (!is.null(fn$return_type$gi) && !is.na(fn$return_type$gi) && fn$return_type$gi != "none") {
    sprintf("#' @return %s", fn$return_type$gi)
  } else {
    "#' @return Return value from C function"
  }

  # Determine family/category from function name pattern
  # Use specific subcategories to keep groups manageable (5-20 functions each)
  family <- if (grepl("^gtk_window_", fn$c_symbol)) {
    "gtk-windows"
  } else if (grepl("^gtk_button_|^gtk_toggle_button_|^gtk_check_button_|^gtk_radio_button_", fn$c_symbol)) {
    "gtk-buttons"
  } else if (grepl("^gtk_box_|^gtk_grid_|^gtk_paned_", fn$c_symbol)) {
    "gtk-layout"
  } else if (grepl("^gtk_label_|^gtk_entry_|^gtk_text_", fn$c_symbol)) {
    "gtk-text"
  } else if (grepl("^gtk_dialog_|^gtk_message_dialog_|^gtk_about_dialog_", fn$c_symbol)) {
    "gtk-dialogs"
  } else if (grepl("^gtk_file_chooser_|^gtk_file_filter_", fn$c_symbol)) {
    "gtk-file-choosers"
  } else if (grepl("^gtk_tree_view_|^gtk_tree_model_|^gtk_tree_selection_|^gtk_list_store_|^gtk_tree_store_", fn$c_symbol)) {
    "gtk-trees"
  } else if (grepl("^gtk_menu_|^gtk_menu_item_|^gtk_menu_bar_|^gtk_popover_", fn$c_symbol)) {
    "gtk-menus"
  } else if (grepl("^gtk_image_|^gtk_picture_|^gtk_icon_", fn$c_symbol)) {
    "gtk-images"
  } else if (grepl("^gtk_application_|^gtk_application_window_", fn$c_symbol)) {
    "gtk-application"
  } else if (grepl("^gtk_widget_", fn$c_symbol)) {
    "gtk-widget"
  } else if (grepl("^gtk_", fn$c_symbol)) {
    "gtk-other"
  } else if (grepl("^gdk_display_|^gdk_monitor_|^gdk_surface_", fn$c_symbol)) {
    "gdk-display"
  } else if (grepl("^gdk_event_|^gdk_device_", fn$c_symbol)) {
    "gdk-events"
  } else if (grepl("^gdk_texture_|^gdk_pixbuf_", fn$c_symbol)) {
    "gdk-graphics"
  } else if (grepl("^gdk_", fn$c_symbol)) {
    "gdk-other"
  } else if (grepl("^g_file_|^g_file_info_", fn$c_symbol)) {
    "gio-files"
  } else if (grepl("^g_application_|^g_app_info_", fn$c_symbol)) {
    "gio-applications"
  } else if (grepl("^g_settings_", fn$c_symbol)) {
    "gio-settings"
  } else if (grepl("^g_dbus_", fn$c_symbol)) {
    "gio-dbus"
  } else if (grepl("^g_io_|^g_input_stream_|^g_output_stream_", fn$c_symbol)) {
    "gio-streams"
  } else if (grepl("^g_list_|^g_slist_|^g_queue_", fn$c_symbol)) {
    "glib-lists"
  } else if (grepl("^g_hash_table_|^g_hash_", fn$c_symbol)) {
    "glib-hash"
  } else if (grepl("^g_string_|^g_str[a-z]*_", fn$c_symbol)) {
    "glib-strings"
  } else if (grepl("^g_variant_", fn$c_symbol)) {
    "glib-variants"
  } else if (grepl("^g_date_time_|^g_time_", fn$c_symbol)) {
    "glib-datetime"
  } else if (grepl("^g_main_|^g_source_|^g_idle_|^g_timeout_", fn$c_symbol)) {
    "glib-mainloop"
  } else if (grepl("^g_error_|^g_log_|^g_message_", fn$c_symbol)) {
    "glib-errors"
  } else if (grepl("^g_bytes_|^g_byte_array_", fn$c_symbol)) {
    "glib-bytes"
  } else if (grepl("^g_object_|^g_signal_", fn$c_symbol)) {
    "gobject-core"
  } else if (grepl("^g_", fn$c_symbol)) {
    "glib-other"
  } else {
    tolower(namespace)
  }

  # Build roxygen block with @rdname to combine into single Rd file
  roxygen_lines <- c(
    sprintf("#' @rdname %s", family),
    sprintf("#' @title %s", r_name),
    "#'",
    param_docs,
    ret_desc,
    "#' @export"
  )
  roxygen_block <- paste(roxygen_lines, collapse = "\n")

  paste0("\n", roxygen_block, "\n", r_name, " <- function(", args_csv, ") {\n",
         "  .Call(\"R_", fn$c_symbol, "\"", call_args, ")\n}\n")
}
