nonempty <- function(x) !is.null(x) && length(x) == 1L && !is.na(x) && nchar(x) > 0

#' @keywords internal
generate_r_file <- function(parsed, namespace, seen_global = NULL, callbacks_by_name = list()) {
  local_seen <- character()
  unique_fns <- Filter(function(f) {
    sym <- f$c_symbol
    if (sym %in% local_seen) return(FALSE)
    if (!is.null(seen_global) && sym %in% seen_global$symbols) return(FALSE)
    local_seen <<- c(local_seen, sym)
    TRUE
  }, parsed$functions)
  r_fns <- sapply(unique_fns, function(fn) generate_r_function(fn, namespace, callbacks_by_name))
  r_fns <- r_fns[nchar(r_fns) > 0]

  enums <- sapply(parsed$enums, function(e) {
    vals <- paste0(toupper(names(e$values)), " <- ", e$values)
    sprintf("\n# %s\n%s", e$name, paste(vals, collapse="\n"))
  })
  paste(c("# Autogenerated R wrappers", r_fns, "\n# Enumerations", enums),
        collapse="\n")
}

r_name_from_c <- function(c_symbol, namespace) {
  pts <- strsplit(c_symbol, "_")[[1]]
  if (length(pts) <= 1) return(c_symbol)
  tail <- paste0(
    toupper(substring(pts[-1], 1, 1)),
    substring(pts[-1], 2),
    collapse = ""
  )
  paste0(pts[1], tail)
}

generate_r_function <- function(fn, namespace, callbacks_by_name = list()) {
  if (!nonempty(fn$c_symbol)) return(skip(fn, "no c_symbol"))

  MIN_VERSIONS <- list(
    "GLib"      = "2.56",
    "GObject"   = "2.56",
    "Gio"       = "2.56",
    "Gdk"       = "4.12",
    "Gtk"       = "4.12",
    "Pango"     = "1.50",
    "GdkPixbuf" = "2.42"
  )

  namespace_detect <- NULL
  if (!is.null(fn$c_symbol)) {
    if (grepl("^g_(?!tk_|dk_)", fn$c_symbol, perl=TRUE)) {
      if (grepl("^g_object_", fn$c_symbol)) namespace_detect <- "GObject"
      else if (grepl("^g_file_|^g_app_|^g_settings_|^g_dbus_", fn$c_symbol)) namespace_detect <- "Gio"
      else namespace_detect <- "GLib"
    } else if (grepl("^gdk_pixbuf_", fn$c_symbol)) {
      namespace_detect <- "GdkPixbuf"
    } else if (grepl("^gdk_", fn$c_symbol)) {
      namespace_detect <- "Gdk"
    } else if (grepl("^gtk_", fn$c_symbol)) {
      namespace_detect <- "Gtk"
    } else if (grepl("^pango_", fn$c_symbol)) {
      namespace_detect <- "Pango"
    }
  }

  if (!is.null(namespace_detect) && !is.null(fn$version) && !is.na(fn$version)) {
    min_version <- MIN_VERSIONS[[namespace_detect]]
    if (!is.null(min_version) && compareVersion(fn$version, min_version) > 0) {
      return(skip(fn, sprintf("version filter: %s > %s for %s", fn$version, min_version, namespace_detect)))
    }
  }

  newer_types <- c(
    "GdkDmabufTextureBuilder", "GdkMemoryTextureBuilder",
    "GdkCicpParams", "GdkColorState",
    "GtkSymbolicPaintable",
    "GdkToplevelCapabilities",
    "GtkPopoverBin"
  )

  all_types <- paste(c(fn$return_type, sapply(fn$params, function(p) p$type)), collapse = " ")
  for (newer_type in newer_types) {
    if (grepl(newer_type, all_types, fixed = TRUE)) {
      return(skip(fn, sprintf("references newer type %s", newer_type)))
    }
  }

  if (grepl("^gdk_rgba_print|^gtk_svg_error_quark", fn$c_symbol)) {
    return(skip(fn, "explicit name skip"))
  }

  if (grepl("^_|^g_osx_|^g_win32_|^g_msys_|^gtk_osx_|^g_unix_|^g_atomic_|^g_io_module_|^g_once_init_|^gtk_print_|^gtk_printer_|^gtk_enumerate_printers|^g_pointer_bit_|^g_dtls_|^g_tls_|^gtk_page_|^g_dbus_|^g_subprocess_|_unix_fd|_unix_user|_unix_pid|gdk_pixbuf_non_anim", fn$c_symbol)) {
    return(skip(fn, "regex blacklist"))
  }

  if (any(sapply(fn$params, function(p)
    identical(p$name,"...") || identical(p$type$gi,"GLib.VarArgs")))) {
    return(skip(fn, "variadic"))
  }

  roles <- classify_param_roles(fn$params, callbacks_by_name)

  is_destroy_typed <- function(gi) {
    if (is.null(gi) || is.na(gi)) return(FALSE)
    gi %in% c("GLib.DestroyNotify", "DestroyNotify", "GDestroyNotify") ||
      grepl("DestroyNotify$", gi)
  }
  for (i in seq_along(fn$params)) {
    p <- fn$params[[i]]
    if (!identical(p$direction, "in")) next
    if (looks_like_callback(p$type$gi) && roles[i] == "normal" &&
        !is_destroy_typed(p$type$gi)) {
      return(skip(fn, sprintf("param %d (%s) looks like callback but no role", i, p$type$gi)))
    }
  }

  for (i in seq_along(fn$params)) {
    if (roles[i] != "callback") next
    cb_def <- callback_lookup(callbacks_by_name, fn$params[[i]]$type$gi)
    if (is.null(cb_def)) return(skip(fn, sprintf("no <callback> def for param %d (%s)", i, fn$params[[i]]$type$gi)))
    if (!isTRUE(callback_signature(cb_def)$ok)) {
      return(skip(fn, sprintf("callback %s rejected by signature check", cb_def$name)))
    }
  }

  r_name <- r_name_from_c(fn$c_symbol, namespace)

  # Visible "in" params: drop user_data and destroy.
  visible_in <- list()
  visible_idx_in_params <- integer()
  for (i in seq_along(fn$params)) {
    p <- fn$params[[i]]
    if (!identical(p$direction, "in")) next
    if (roles[i] %in% c("user_data", "destroy")) next
    visible_in[[length(visible_in) + 1L]] <- p
    visible_idx_in_params <- c(visible_idx_in_params, i)
  }

  args <- if (length(visible_in) > 0) {
    sapply(visible_in, function(p) {
      name <- p$name
      name <- gsub("[^a-zA-Z0-9_]", "_", name)
      if (name %in% c("if", "else", "for", "while", "function", "return", "break", "next", "repeat", "in", "NULL", "TRUE", "FALSE", "NA", "NaN", "Inf")) {
        name <- paste0(name, "_")
      }
      if (grepl("^[0-9]", name)) {
        name <- paste0("x", name)
      }
      name
    })
  } else {
    character(0)
  }

  args_csv  <- paste(args, collapse=", ")

  if (length(args) > 0) {
    converted_args <- sapply(seq_along(visible_in), function(i) {
      p <- visible_in[[i]]
      arg_name <- args[i]
      gi <- p$type$gi

      integer_types <- c("gint", "guint", "gint8", "guint8", "gint16", "guint16",
                         "gint32", "guint64", "gulong", "gsize")

      param_role <- roles[visible_idx_in_params[i]]
      ct <- p$type$c
      is_ptr_ct <- !is.null(ct) && !is.na(ct) &&
        (grepl("\\*", ct) || ct %in% c("gpointer", "gconstpointer"))
      is_array <- isTRUE(p$type$is_array)
      if (param_role == "callback") {
        arg_name
      } else if (is_ptr_ct || is_array) {
        # Pointer / array param — never coerce. The element GI may be
        # integral (e.g. const guchar* arrays have GI "guint8") but the
        # value is a pointer to bytes, not a number.
        arg_name
      } else if (!is.null(gi) && gi %in% integer_types) {
        sprintf("as.integer(%s)", arg_name)
      } else {
        arg_name
      }
    })
    call_args <- paste0(", ", paste(converted_args, collapse=", "))
  } else {
    call_args <- ""
  }

  param_docs <- if (length(visible_in) > 0) {
    sapply(seq_along(visible_in), function(i) {
      p <- visible_in[[i]]
      param_name <- args[i]
      type_desc <- if (roles[visible_idx_in_params[i]] == "callback") {
        sprintf("function — %s callback", p$type$gi)
      } else if (!is.null(p$type$gi) && !is.na(p$type$gi)) {
        p$type$gi
      } else if (!is.null(p$type$c) && !is.na(p$type$c)) {
        p$type$c
      } else {
        "parameter"
      }
      sprintf("#' @param %s %s", param_name, type_desc)
    })
  } else {
    character(0)
  }

  ret_desc <- if (!is.null(fn$return_type$gi) && !is.na(fn$return_type$gi) && fn$return_type$gi != "none") {
    sprintf("#' @return %s", fn$return_type$gi)
  } else {
    "#' @return Return value from C function"
  }

  family <- if (grepl("^gtk_window_", fn$c_symbol)) {
    "gtk-windows"
  } else if (grepl("^gtk_button_|^gtk_toggle_button_|^gtk_check_button_|^gtk_radio_button_", fn$c_symbol)) {
    "gtk-buttons"
  } else if (grepl("^gtk_box_|^gtk_grid_|^gtk_paned_", fn$c_symbol)) {
    "gtk-layout"
  } else if (grepl("^gtk_label_|^gtk_entry_|^gtk_text_", fn$c_symbol)) {
    "gtk-text"
  } else if (grepl("^gtk_dialog_|^gtk_message_dialog_|^gtk_about_dialog_", fn$c_symbol)) {
    "gtk-dialogs"
  } else if (grepl("^gtk_file_chooser_|^gtk_file_filter_", fn$c_symbol)) {
    "gtk-file-choosers"
  } else if (grepl("^gtk_tree_view_|^gtk_tree_model_|^gtk_tree_selection_|^gtk_list_store_|^gtk_tree_store_", fn$c_symbol)) {
    "gtk-trees"
  } else if (grepl("^gtk_menu_|^gtk_menu_item_|^gtk_menu_bar_|^gtk_popover_", fn$c_symbol)) {
    "gtk-menus"
  } else if (grepl("^gtk_image_|^gtk_picture_|^gtk_icon_", fn$c_symbol)) {
    "gtk-images"
  } else if (grepl("^gtk_application_|^gtk_application_window_", fn$c_symbol)) {
    "gtk-application"
  } else if (grepl("^gtk_widget_", fn$c_symbol)) {
    "gtk-widget"
  } else if (grepl("^gtk_", fn$c_symbol)) {
    "gtk-other"
  } else if (grepl("^gdk_display_|^gdk_monitor_|^gdk_surface_", fn$c_symbol)) {
    "gdk-display"
  } else if (grepl("^gdk_event_|^gdk_device_", fn$c_symbol)) {
    "gdk-events"
  } else if (grepl("^gdk_texture_|^gdk_pixbuf_", fn$c_symbol)) {
    "gdk-graphics"
  } else if (grepl("^gdk_", fn$c_symbol)) {
    "gdk-other"
  } else if (grepl("^g_file_|^g_file_info_", fn$c_symbol)) {
    "gio-files"
  } else if (grepl("^g_application_|^g_app_info_", fn$c_symbol)) {
    "gio-applications"
  } else if (grepl("^g_settings_", fn$c_symbol)) {
    "gio-settings"
  } else if (grepl("^g_dbus_", fn$c_symbol)) {
    "gio-dbus"
  } else if (grepl("^g_io_|^g_input_stream_|^g_output_stream_", fn$c_symbol)) {
    "gio-streams"
  } else if (grepl("^g_list_|^g_slist_|^g_queue_", fn$c_symbol)) {
    "glib-lists"
  } else if (grepl("^g_hash_table_|^g_hash_", fn$c_symbol)) {
    "glib-hash"
  } else if (grepl("^g_string_|^g_str[a-z]*_", fn$c_symbol)) {
    "glib-strings"
  } else if (grepl("^g_variant_", fn$c_symbol)) {
    "glib-variants"
  } else if (grepl("^g_date_time_|^g_time_", fn$c_symbol)) {
    "glib-datetime"
  } else if (grepl("^g_main_|^g_source_|^g_idle_|^g_timeout_", fn$c_symbol)) {
    "glib-mainloop"
  } else if (grepl("^g_error_|^g_log_|^g_message_", fn$c_symbol)) {
    "glib-errors"
  } else if (grepl("^g_bytes_|^g_byte_array_", fn$c_symbol)) {
    "glib-bytes"
  } else if (grepl("^g_object_|^g_signal_", fn$c_symbol)) {
    "gobject-core"
  } else if (grepl("^g_", fn$c_symbol)) {
    "glib-other"
  } else {
    tolower(namespace)
  }

  roxygen_lines <- c(
    sprintf("#' @rdname %s", family),
    sprintf("#' @title %s", r_name),
    "#'",
    param_docs,
    ret_desc,
    "#' @export"
  )
  roxygen_block <- paste(roxygen_lines, collapse = "\n")

  ret_gi <- if (is.null(fn$return_type$gi)) "none" else fn$return_type$gi
  out_params <- Filter(function(p) p$direction %in% c("out", "inout"), fn$params)

  unwrap_suffix <- ""
  wrap_invisible <- FALSE

  if (ret_gi != "none" && length(out_params) == 0) {
    unwrap_suffix <- "$result"
  } else if (ret_gi == "none" && length(out_params) == 1) {
    out_name <- gsub("[^a-zA-Z0-9_]", "_", out_params[[1]]$name)
    unwrap_suffix <- paste0("$", out_name)
  } else if (ret_gi == "none" && length(out_params) == 0) {
    wrap_invisible <- TRUE
  }

  call_expr <- paste0(".Call(\"R_", fn$c_symbol, "\"", call_args, ")", unwrap_suffix)
  if (wrap_invisible) {
    call_expr <- paste0("invisible(", call_expr, ")")
  }

  paste0("\n", roxygen_block, "\n", r_name, " <- function(", args_csv, ") {\n",
         "  ", call_expr, "\n}\n")
}
